# Settings for libraries used by specific LAMMPS packages
# this file is auto-edited when those packages are included/excluded

PKG_INC =   -DLMP_PYTHON -I../../lib/awpmd/ivutils/include -I../../lib/awpmd/systems/interact 
PKG_PATH =  
PKG_LIB =   
PKG_CPP_DEPENDS = 
PKG_LINK_DEPENDS = 

PKG_SYSINC =  $(python_SYSINC) 
PKG_SYSLIB =  $(python_SYSLIB) 
PKG_SYSPATH = 
